---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: elct9620/mrb-compiler

inputs:
- name: example

outputs:
- name: build

run:
  path: mruby-compiler
  args:
    - $(pwd)/example
    - $(pwd)
