---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: elct9620/mrb-compiler

inputs:
- name: example

outputs:
- name: build

run:
  path: sh
  args:
    - -exc
    - |
      export VERSION=$(date +"%Y%m%d%H%M%S")
      echo "Release $VERSION" > build/name
      echo "1.0.0-$VERSION" > build/tag
      mruby-compiler $(pwd)/example $(pwd)/build
