---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine

inputs:
- name: build

run:
  path: sh
  args:
    - -exc
    - |
      ./build/host/bin/example "puts true"
